# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'Mochi'
copyright = '2019, Argonne National Laboratory'
author = 'Argonne National Laboratory'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'breathe',
    'recommonmark',
    'sphinx.ext.todo',
    'sphinx_copybutton',
    'sphinx.ext.autosectionlabel',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'logo_only': True
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_logo = '_static/mochi-logo.png'

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Mochidoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Mochi.tex', 'Mochi Documentation',
     'Argonne National Laboratory', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'mochi', 'Mochi Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Mochi', 'Mochi Documentation',
     author, 'Mochi', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

here = os.path.dirname(os.path.realpath(__file__))

def get_thallium_classes_from_xml(doxygen_xml_path):
    """Extract class names from the thallium namespace XML file."""
    from bs4 import BeautifulSoup
    namespace_file = os.path.join(doxygen_xml_path, 'namespacethallium.xml')
    if not os.path.exists(namespace_file):
        return []
    with open(namespace_file, 'r') as f:
        soup = BeautifulSoup(f, 'xml')
    classes = [
        innerclass.get_text().replace(' ', '') for innerclass in soup.find_all('innerclass')
    ]
    return sorted(classes)


def generate_thallium_api():
    # Download thallium as an archive
    import urllib.request
    urllib.request.urlretrieve(
        'https://github.com/mochi-hpc/mochi-thallium/archive/refs/heads/main.zip',
        'mochi-thallium.zip')
    # Unzip the file
    import zipfile
    with zipfile.ZipFile('mochi-thallium.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
    # All doxygen
    import subprocess
    subprocess.call('cd mochi-thallium-main && doxygen', shell=True)
    # Move xml folder
    import shutil
    shutil.rmtree('thallium/doxygen', ignore_errors=True)
    shutil.move('mochi-thallium-main/doc/xml',
                'thallium/doxygen')
    # Remove mochi-thallium.zip and mochi-thallium-main
    os.remove('mochi-thallium.zip')
    shutil.rmtree('mochi-thallium-main')
    # Get class names from the XML files
    classes = get_thallium_classes_from_xml('thallium/doxygen')
    # Generate API from template
    import jinja2
    environment = jinja2.Environment(loader=jinja2.FileSystemLoader('.'))
    template = environment.get_template('thallium/api.rst.in')
    with open('thallium/api.rst', 'w+') as f:
        f.write(template.render(classes=classes))

def get_margo_headers_from_xml(doxygen_xml_path):
    """Extract header file names from the doxygen index.xml file."""
    from bs4 import BeautifulSoup
    index_file = os.path.join(doxygen_xml_path, 'index.xml')
    if not os.path.exists(index_file):
        return []
    with open(index_file, 'r') as f:
        soup = BeautifulSoup(f, 'xml')
    headers = []
    for compound in soup.find_all('compound', kind='file'):
        name_elem = compound.find('name')
        if name_elem:
            name = name_elem.get_text()
            if name.endswith('.h'):
                headers.append(name)
    # Sort with margo.h first, then alphabetically
    headers = sorted(headers)
    return headers


def generate_margo_api():
    # Download margo as an archive
    import urllib.request
    urllib.request.urlretrieve(
        'https://github.com/mochi-hpc/mochi-margo/archive/refs/heads/main.zip',
        'mochi-margo.zip')
    # Unzip the file
    import zipfile
    with zipfile.ZipFile('mochi-margo.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
    # Call doxygen
    import subprocess
    subprocess.call('cd mochi-margo-main && doxygen', shell=True)
    # Move xml folder
    import shutil
    shutil.rmtree('margo/doxygen', ignore_errors=True)
    shutil.move('mochi-margo-main/doc/xml',
                'margo/doxygen')
    # Remove mochi-margo.zip and mochi-margo-main
    os.remove('mochi-margo.zip')
    shutil.rmtree('mochi-margo-main')
    # Get header files from the doxygen XML files
    headers = get_margo_headers_from_xml('margo/doxygen')
    # Generate API from template
    import jinja2
    environment = jinja2.Environment(loader=jinja2.FileSystemLoader('.'))
    template = environment.get_template('margo/api.rst.in')
    with open('margo/api.rst', 'w+') as f:
        f.write(template.render(
            headers=headers))


generate_thallium_api()
generate_margo_api()

breathe_default_project = 'thallium'
breathe_projects = {
    'thallium': os.path.join(here, 'thallium', 'doxygen'),
    'margo': os.path.join(here, 'margo', 'doxygen')
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

def setup(app):
    app.add_css_file('custom.css')
