# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'Mochi'
copyright = '2019, Argonne National Laboratory'
author = 'Argonne National Laboratory'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'breathe',
    'recommonmark',
    'sphinx.ext.todo',
    'sphinx_copybutton',
    'sphinx.ext.autosectionlabel',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'logo_only': True
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_logo = '_static/mochi-logo.png'

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Mochidoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Mochi.tex', 'Mochi Documentation',
     'Argonne National Laboratory', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'mochi', 'Mochi Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Mochi', 'Mochi Documentation',
     author, 'Mochi', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

here = os.path.dirname(os.path.realpath(__file__))


def get_classes_from_xml(doxygen_xml_path, namespace, exclude_classes=None):
    """Extract class names from a namespace XML file.

    Args:
        doxygen_xml_path: Path to the doxygen XML output directory
        namespace: The C++ namespace to extract classes from
        exclude_classes: List of class name patterns to exclude (matched as prefixes)

    Returns:
        Sorted list of fully-qualified class names
    """
    from bs4 import BeautifulSoup
    namespace_file = os.path.join(doxygen_xml_path, f'namespace{namespace}.xml')
    if not os.path.exists(namespace_file):
        return []
    with open(namespace_file, 'r') as f:
        soup = BeautifulSoup(f, 'xml')
    exclude_classes = exclude_classes or []
    exclude_prefixes = [f'{namespace}::{pattern}' for pattern in exclude_classes]
    classes = []
    for innerclass in soup.find_all('innerclass'):
        class_name = innerclass.get_text()
        if class_name and class_name.startswith(f'{namespace}::'):
            # Skip excluded classes
            if any(class_name.startswith(prefix) for prefix in exclude_prefixes):
                continue
            # Normalize whitespace in template specializations
            class_name = class_name.replace(' ', '')
            classes.append(class_name)
    return sorted(classes)


def get_headers_from_xml(doxygen_xml_path, exclude_headers=None):
    """Extract header file names from the doxygen index.xml file.

    Args:
        doxygen_xml_path: Path to the doxygen XML output directory
        exclude_headers: List of header filenames to exclude

    Returns:
        Sorted list of header file names
    """
    from bs4 import BeautifulSoup
    index_file = os.path.join(doxygen_xml_path, 'index.xml')
    if not os.path.exists(index_file):
        return []
    with open(index_file, 'r') as f:
        soup = BeautifulSoup(f, 'xml')
    exclude_headers = exclude_headers or []
    headers = []
    for compound in soup.find_all('compound', kind='file'):
        name_elem = compound.find('name')
        if name_elem:
            name = name_elem.get_text()
            if name.endswith('.h') and name not in exclude_headers:
                headers.append(name)
    return sorted(headers)


def generate_cpp_api_rst(name, classes):
    """Generate the cpp_api.rst content for a library's C++ API.

    Args:
        name: Library name (used as the breathe project name)
        classes: List of C++ class names to document

    Returns:
        String containing the RST content
    """
    lines = ['C++ API Documentation', '=====================', '']
    for cls in classes:
        lines.append(cls)
        lines.append('-' * len(cls))
        lines.append('')
        lines.append(f'.. doxygenclass:: {cls}')
        lines.append('   :members:')
        lines.append(f'   :project: {name}')
        lines.append('')
    return '\n'.join(lines)


def generate_c_api_rst(name, headers):
    """Generate the c_api.rst content for a library's C API.

    Args:
        name: Library name (used as the breathe project name)
        headers: List of C header files to document

    Returns:
        String containing the RST content
    """
    lines = ['C API Documentation', '===================', '']
    for header in headers:
        lines.append(header)
        lines.append('-' * len(header))
        lines.append('')
        lines.append(f'.. doxygenfile:: {header}')
        lines.append(f'   :project: {name}')
        lines.append('')
    return '\n'.join(lines)


def generate_library_api(name,
                         namespace=None,
                         exclude_classes=None,
                         exclude_headers=None,
                         branch='main',
                         github_org='mochi-hpc'):
    """Generate API documentation for a Mochi library.

    Downloads the library source from GitHub, runs doxygen, and generates
    the api.rst file. Automatically detects C++ classes (from namespace XML)
    and/or C headers (from index.xml).

    Args:
        name: Library name (e.g., 'margo', 'thallium')
        namespace: C++ namespace name (defaults to library name if not specified)
        exclude_classes: List of class name patterns to exclude from C++ docs
        exclude_headers: List of header filenames to exclude from C docs
        branch: Git branch to download (default: 'main')
        github_org: GitHub organization (default: 'mochi-hpc')

    Returns:
        Path to the doxygen XML directory
    """
    import shutil
    import subprocess
    import urllib.request
    import zipfile

    # Use library name as namespace if not specified
    if namespace is None:
        namespace = name

    repo_name = f'mochi-{name}'
    zip_filename = f'{repo_name}.zip'
    extracted_dir = f'{repo_name}-{branch}'
    doxygen_output = f'{name}/doxygen'

    # Download library as an archive
    url = f'https://github.com/{github_org}/{repo_name}/archive/refs/heads/{branch}.zip'
    urllib.request.urlretrieve(url, zip_filename)

    # Unzip the file
    with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
        zip_ref.extractall('.')

    # Run doxygen only if Doxyfile exists
    has_doxyfile = os.path.exists(f'{extracted_dir}/Doxyfile')
    if has_doxyfile:
        subprocess.call(f'cd {extracted_dir} && doxygen', shell=True)

        # Move xml folder
        shutil.rmtree(doxygen_output, ignore_errors=True)
        shutil.move(f'{extracted_dir}/doc/xml', doxygen_output)

    # Merge library's docs folder with the repository's docs folder
    library_docs_dir = f'{extracted_dir}/docs'
    repo_docs_dir = os.path.dirname(here)  # Parent of source/ is docs/
    if os.path.isdir(library_docs_dir):
        for item in os.listdir(library_docs_dir):
            src = os.path.join(library_docs_dir, item)
            dst = os.path.join(repo_docs_dir, item)
            if os.path.isdir(src):
                if os.path.exists(dst):
                    # Merge directories recursively
                    for root, dirs, files in os.walk(src):
                        rel_path = os.path.relpath(root, src)
                        dst_root = os.path.join(dst, rel_path) if rel_path != '.' else dst
                        os.makedirs(dst_root, exist_ok=True)
                        for file in files:
                            shutil.copy2(os.path.join(root, file), os.path.join(dst_root, file))
                else:
                    shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)

    # Clean up downloaded files
    os.remove(zip_filename)
    shutil.rmtree(extracted_dir)

    # Generate API documentation only if doxygen was run
    if has_doxyfile:
        # Extract classes and headers from doxygen XML
        classes = get_classes_from_xml(doxygen_output, namespace, exclude_classes)
        headers = get_headers_from_xml(doxygen_output, exclude_headers)

        # Generate cpp_api.rst if C++ classes found
        if classes:
            cpp_api_content = generate_cpp_api_rst(name, classes)
            with open(f'{name}/cpp_api.rst', 'w') as f:
                f.write(cpp_api_content)

        # Generate c_api.rst if C headers found
        if headers:
            c_api_content = generate_c_api_rst(name, headers)
            with open(f'{name}/c_api.rst', 'w') as f:
                f.write(c_api_content)

        return os.path.join(here, doxygen_output)

    return None


# Generate API documentation for libraries
breathe_projects = {}


def register_library(name, **kwargs):
    """Generate library API and register with breathe if Doxyfile exists."""
    result = generate_library_api(name, **kwargs)
    if result is not None:
        breathe_projects[name] = result


register_library(
    'thallium',
    exclude_classes=[
        'is_std_function_object',
        'remove_class',
        'strip_function_object',
        'unwrap_refwrapper',
    ]
)

register_library('margo')
register_library('yokan')
register_library('warabi')
register_library('flock')
register_library('bedrock')

breathe_default_project = 'thallium'

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

def setup(app):
    app.add_css_file('custom.css')
