[margo]
use_progress_thread = true

  [[argobots.pools]]
  name = "my_pool_1"
  kind = "fifo_wait"
  access = "mpmc"

  [[argobots.pools]]
  name = "my_pool_2"
  kind = "fifo_wait"
  access = "mpmc"

[libraries]
module_a = "path/to/libModuleA.so"
module_b = "path/to/libModuleB.so"

[[providers]]
name = "my_provider_1"
type = "module_a"
provider_id = 1

[[providers]]
name = "my_provider_2"
type = "module_b"
provider_id = 2
