name: build

on: [push,pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop
    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e code repo add mochi-spack-packages
    - name: Install Package from Spack
      run: |
        spack -e code install --fail-fast
    - name: Show Spack installed packages for debugging
      run: |
        spack -e code find -dlv
    - name: Build all the examples
      run: |
        eval `spack env activate --sh code`
        mkdir build
        cd build
        cmake ../code
        make
